import { Inter } from "next/font/google";

import "../styles/index.scss";
import "../styles/globals.css";

import SessionWrapper from "@/components/sessionWrapper";
import TranslateWrapper from "@/components/translateWrapper";
import GenericWrapper from "@/components/genericWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TranslateWrapper>
          <GenericWrapper>
            {/* <SessionWrapper > */}
            {children}
            {/* </SessionWrapper> */}
          </GenericWrapper>
        </TranslateWrapper>
      </body>
    </html>
  );
}
